# Generated by Django 3.1.12 on 2021-09-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_export', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='file',
            field=models.FileField(null=True, upload_to='export'),
        ),
    ]
