# Generated by Django 3.1.12 on 2021-09-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_export', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='download_resources',
            field=models.BooleanField(default=False, verbose_name='Download resources'),
        ),
        migrations.AddField(
            model_name='export',
            name='in_progress',
            field=models.BooleanField(default=False, verbose_name='completed at'),
        ),
        migrations.AddField(
            model_name='export',
            name='md5',
            field=models.CharField(default='', max_length=128, verbose_name='md5 of file'),
        ),
        migrations.AddField(
            model_name='export',
            name='only_finished',
            field=models.BooleanField(default=False, help_text='If true - it exports only finished tasks', verbose_name='Only finished'),
        ),
        migrations.AddField(
            model_name='export',
            name='task_ids',
            field=models.JSONField(default=[], help_text='If list is empty - download all tasks', verbose_name='Task ids list'),
        ),
    ]
