# Generated by Django 3.1.12 on 2021-09-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_export', '0002_auto_20210906_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='export',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='export',
            name='in_progress',
        ),
        migrations.AddField(
            model_name='export',
            name='finished_at',
            field=models.DateTimeField(default=None, help_text='finished time', null=True, verbose_name='finished at'),
        ),
        migrations.AddField(
            model_name='export',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('in_progress', 'In progress'), ('failed', 'Failed'), ('completed', 'Completed')], default='created', max_length=64, verbose_name='Exporting status'),
        ),
    ]
