# Generated by Django 3.1.13 on 2021-09-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_export', '0004_export_counters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='task_ids',
            field=models.JSONField(default=list, help_text='If list is empty - download all tasks', verbose_name='Task ids list'),
        ),
    ]
