# Generated by Django 3.1.12 on 2021-09-07 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_export', '0005_auto_20210907_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exports', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='export',
            name='finished_at',
            field=models.DateTimeField(default=None, help_text='Complete or fail time', null=True, verbose_name='finished at'),
        ),
    ]
