# Generated by Django 3.2.16 on 2023-03-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_export', '0007_auto_20230327_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertedformat',
            name='traceback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
