# Generated by Django 5.1.15 on 2026-01-14 10:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_export", "0010_alter_convertedformat_export_type"),
        ("projects", "0034_project_annotator_evaluation_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PdfExportJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "export_id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique export job identifier (UUID)",
                        max_length=36,
                        unique=True,
                    ),
                ),
                (
                    "include_page_images",
                    models.BooleanField(
                        default=True, help_text="Include rendered page images (PNG)"
                    ),
                ),
                (
                    "include_w3c",
                    models.BooleanField(
                        default=False, help_text="Include W3C Web Annotation format"
                    ),
                ),
                (
                    "render_dpi",
                    models.PositiveIntegerField(
                        default=200, help_text="DPI for page image rendering"
                    ),
                ),
                (
                    "task_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Specific task IDs to export (empty = all tasks)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("partial", "Partial success"),
                            ("failed", "Failed"),
                        ],
                        default="created",
                        help_text="Export job status",
                        max_length=32,
                    ),
                ),
                (
                    "progress_percent",
                    models.PositiveIntegerField(
                        default=0, help_text="Export progress (0-100)"
                    ),
                ),
                (
                    "progress_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Human-readable progress message",
                    ),
                ),
                (
                    "total_documents",
                    models.PositiveIntegerField(
                        default=0, help_text="Total documents to export"
                    ),
                ),
                (
                    "completed_documents",
                    models.PositiveIntegerField(
                        default=0, help_text="Successfully exported documents"
                    ),
                ),
                (
                    "failed_documents",
                    models.PositiveIntegerField(
                        default=0, help_text="Failed documents"
                    ),
                ),
                (
                    "total_pages",
                    models.PositiveIntegerField(
                        default=0, help_text="Total pages exported"
                    ),
                ),
                (
                    "total_annotations",
                    models.PositiveIntegerField(
                        default=0, help_text="Total annotations exported"
                    ),
                ),
                (
                    "output_dir",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Path to export output directory",
                        max_length=512,
                    ),
                ),
                (
                    "zip_file",
                    models.FileField(
                        blank=True,
                        help_text="ZIP archive of export bundle",
                        null=True,
                        upload_to="export",
                    ),
                ),
                (
                    "file_size_bytes",
                    models.BigIntegerField(
                        blank=True, help_text="Size of ZIP file in bytes", null=True
                    ),
                ),
                (
                    "errors",
                    models.JSONField(
                        blank=True, default=list, help_text="List of export errors"
                    ),
                ),
                (
                    "traceback",
                    models.TextField(
                        blank=True, default="", help_text="Traceback for fatal errors"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the export was created"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When export processing started",
                        null=True,
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When export completed or failed",
                        null=True,
                    ),
                ),
                (
                    "export_schema_version",
                    models.CharField(
                        default="1.0.0",
                        help_text="Version of the export schema",
                        max_length=32,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who initiated the export",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Label Studio project",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_exports",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "PDF ML Export Job",
                "verbose_name_plural": "PDF ML Export Jobs",
                "db_table": "pdf_export_job",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "-created_at"],
                        name="pdf_export__project_1c3ddf_idx",
                    ),
                    models.Index(
                        fields=["status"], name="pdf_export__status_a02cc1_idx"
                    ),
                    models.Index(
                        fields=["export_id"], name="pdf_export__export__370931_idx"
                    ),
                ],
            },
        ),
    ]
