title: 成对分类
type: community
group: 排名和评分
image: /static/templates/pairwise-classification.png
details: <h1>选择两个项目之一</h1>
config: |
  <View>
    <Header>Select one of two items</Header>
    <Pairwise name="pw" toName="text1,text2" />
    <Text name="text1" value="$pairText1" />
    <Text name="text2" value="$pairText2" />
  </View>
