# Generated by Django 3.1.4 on 2021-04-12 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20210309_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='state',
        ),
    ]
