# Generated by Django 3.1.13 on 2021-09-14 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20210913_0739'),
        ('tasks', '0010_auto_20210914_0032'),
    ]

    operations = [
    ]
