# Generated by Django 3.1.14 on 2022-05-12 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_new_index_anno_result'),
        ('tasks', '0018_manual_migrate_counters'),
    ]

    operations = [
    ]
