# Generated by Django 3.1.14 on 2022-05-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_auto_20220516_0545'),
        ('tasks', '0021_auto_20220515_2358'),
    ]

    operations = [
    ]
