# Generated by Django 3.2.13 on 2022-07-07 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_manual_migrate_counters_again'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='annotation',
            name='task_comple_last_ac_777e69_idx',
        ),
        migrations.RemoveIndex(
            model_name='annotation',
            name='task_comple_last_cr_dedad7_idx',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='last_action',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='last_created_by',
        ),
    ]
