# Generated by Django 3.2.14 on 2022-11-11 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def set_updated_by(apps, _):
    Annotation = apps.get_model('tasks', 'Annotation')
    for obj in Annotation.objects.all().iterator():
        obj.updated_by = obj.task.updated_by
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0028_auto_20220802_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='updated_by',
            field=models.ForeignKey(help_text='Last user who updated this annotation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_annotations', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.RunPython(set_updated_by)
    ]
