# Generated by Django 3.2.13 on 2022-08-08 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_auto_20220707_0652'),
        ('tasks', '0028_auto_20220802_2220'),
    ]

    operations = [
    ]
