# Generated by Django 3.2.14 on 2022-11-01 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_auto_20220802_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='project',
            field=models.ForeignKey(help_text='Project ID for this annotation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='projects.project'),
        ),
    ]
