# Generated by Django 3.2.14 on 2022-10-05 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_auto_20220802_2220'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='annotation',
            name='task_comple_last_ac_777e69_idx',
        ),
        migrations.RemoveIndex(
            model_name='annotation',
            name='task_comple_last_cr_dedad7_idx',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='last_action',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='last_created_by',
        ),
    ]
