# Generated by Django 3.2.16 on 2022-11-21 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20220809_0915'),
        ('tasks', '0029_auto_20220809_0915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AddField(
            model_name='annotation',
            name='project',
            field=models.ForeignKey(help_text='Project ID for this annotation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='projects.project'),
        ),
    ]
