# Generated by Django 3.2.14 on 2022-11-02 11:18

from django.db import migrations

def forward(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    Annotation = apps.get_model('tasks', 'Annotation')
    # projects = Project.objects.all()
    # for project in projects:
    #     Annotation.objects.filter(task__project=project).update(project=project)

    result = []
    for annotation in Annotation.objects.prefetch_related('task').all():
        annotation.project = annotation.task.project
        result.append(annotation)

    Annotation.objects.bulk_update(result, fields=['project'])
        



def backwards(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_annotation_project'),
    ]

    operations = [
        migrations.RunPython(forward, backwards),
    ]
