# Generated by Django 3.2.16 on 2022-11-18 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from tasks.functions import fill_annotations_updated_by

def forward(apps, _):
    fill_annotations_updated_by()

def backward(apps, _):
    pass

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0031_annotation_updated_by'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
