# Generated by Django 3.2.16 on 2022-12-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0034_annotation_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklock',
            name='unique_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
