# Generated by Django 3.2.16 on 2023-03-21 13:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0034_annotation_unique_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='annotation',
            name='task_comple_last_cr_dedad7_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_is_labe_215a18_idx',
        ),
        migrations.AddField(
            model_name='tasklock',
            name='unique_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='ground_truth',
            field=models.BooleanField(default=False, help_text='This annotation is a Ground Truth (ground_truth)', verbose_name='ground_truth'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='unique_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='was_cancelled',
            field=models.BooleanField(default=False, help_text='User skipped the task', verbose_name='was cancelled'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_labeled',
            field=models.BooleanField(default=False, help_text='True if the number of annotations for this task is greater than or equal to the number of maximum_completions for the project', verbose_name='is_labeled'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['project', 'ground_truth'], name='task_comple_project_2cbbfc_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['project', 'was_cancelled'], name='task_comple_project_5c60f3_idx'),
        ),
    ]
