# Generated by Django 3.2.16 on 2022-12-23 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0035_tasklock_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='unique_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tasklock',
            name='unique_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
