# Generated by Django 3.2.16 on 2023-01-18 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0035_auto_20221221_1116'),
        ('tasks', '0036_auto_20221223_1102'),
    ]

    operations = [
    ]
