# Generated by Django 3.2.16 on 2023-02-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0037_merge_0035_auto_20221221_1116_0036_auto_20221223_1102'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['project', 'ground_truth'], name='task_comple_project_2cbbfc_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['project', 'was_cancelled'], name='task_comple_project_5c60f3_idx'),
        ),
    ]
