# Generated by Django 3.2.16 on 2023-03-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_auto_20221005_1620'),
        ('tasks', '0038_auto_20230209_1412'),
    ]

    operations = [
    ]
