# Generated by Django 3.2.16 on 2023-08-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0034_auto_20230103_0709'),
        ('tasks', '0040_auto_20230628_1101'),
    ]

    operations = [
    ]
