# Generated by Django 3.2.20 on 2023-09-06 23:55

from django.db import migrations, models
from django.contrib.postgres.operations import AddIndexConcurrently

class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('tasks', '0043_auto_20230825'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='annotation',
            index=models.Index(
                fields=['project_id', 'id'],
                name='task_completion_project_id_first_idx'
            )
        ),
        AddIndexConcurrently(
            model_name='task',
            index=models.Index(
                fields=['project_id', 'id'],
                name='task_project_id_first_idx'
            )
        )
    ]
