# Generated by Django 3.2.20 on 2023-09-07 01:55

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('tasks', '0043_auto_20230825'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='annotation',
            index=models.Index(fields=['project', 'id'], name='task_comple_project_c7e507_idx'),
        ),
        AddIndexConcurrently(
            model_name='task',
            index=models.Index(fields=['project', 'id'], name='task_project_7b1c80_idx'),
        ),
    ]
