# Generated by Django 3.2.24 on 2024-03-18 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0046_auto_20240314_1957'),
        ('tasks', '0046_prediction_model_run'),
    ]

    operations = [
    ]
