# Generated by Django 5.1.10 on 2025-12-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0055_task_import_tags"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="task",
            new_name="task_import__467338_idx",
            old_name="task_import_batch_idx",
        ),
    ]
