# Generated by Django 5.1.12 on 2025-10-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0057_annotation_proj_result_octlen_idx_async"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="precomputed_agreement",
            field=models.FloatField(
                help_text="Average agreement score for the task",
                null=True,
                verbose_name="precomputed_agreement",
            ),
        ),
    ]
