# Generated by Django 3.2.16 on 2023-05-10 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensortype', models.CharField(choices=[('I', 'IMU'), ('C', 'Camera'), ('M', 'Microphone')], default='I', max_length=1)),
                ('manufacturer', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('date_row', models.IntegerField(default=1)),
                ('time_row', models.IntegerField(default=1)),
                ('timestamp_column', models.IntegerField(default=1)),
                ('relative_absolute', models.CharField(default='relative', max_length=100)),
                ('timestamp_unit', models.CharField(default='seconds', max_length=100)),
                ('format_string', models.CharField(max_length=100, null=True)),
                ('sensor_id_row', models.IntegerField(default=1, null=True)),
                ('sensor_id_column', models.IntegerField(null=True)),
                ('sensor_id_regex', models.CharField(max_length=100, null=True)),
                ('col_names_row', models.IntegerField(default=1)),
                ('comment_style', models.CharField(max_length=100, null=True)),
                ('timezone', models.TextField(default='UTC')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('extra_info', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=100)),
                ('sensor_hash', models.CharField(blank=True, max_length=10)),
                ('sensortype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensormodel.sensortype')),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('begin_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('location', models.TextField(max_length=50)),
                ('position', models.TextField(blank=True, max_length=50)),
                ('sensorlist', models.TextField(blank=True, max_length=500)),
                ('subjectlist', models.TextField(blank=True, max_length=500)),
                ('sensor', models.ManyToManyField(blank=True, to='sensormodel.Sensor')),
                ('subject', models.ManyToManyField(blank=True, to='sensormodel.Subject')),
            ],
        ),
    ]
