# Generated by Django 3.2.14 on 2022-10-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensormodel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensortabel',
            old_name='id_sensor',
            new_name='sensor_id',
        ),
    ]
