# Generated by Django 3.2.14 on 2022-10-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensormodel', '0003_auto_20221010_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='sensor',
        ),
        migrations.AddField(
            model_name='deployment',
            name='sensor',
            field=models.ManyToManyField(to='sensormodel.Sensor'),
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='subject',
        ),
        migrations.AddField(
            model_name='deployment',
            name='subject',
            field=models.ManyToManyField(to='sensormodel.Subject'),
        ),
    ]
