# Generated by Django 3.2.14 on 2022-10-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensormodel', '0006_auto_20221018_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='sensorlist',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='subjectlist',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
