# Generated by Django 3.2.14 on 2022-10-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensormodel', '0007_auto_20221024_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='sensor',
            field=models.ManyToManyField(blank=True, to='sensormodel.Sensor'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='subject',
            field=models.ManyToManyField(blank=True, to='sensormodel.Subject'),
        ),
    ]
