# Generated by Django 3.2.14 on 2022-11-26 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensormodel', '0010_auto_20221121_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='sensors',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensortype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sensormodel.sensortype'),
        ),
    ]
