# Generated by Django 3.2.14 on 2023-01-29 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensormodel', '0012_auto_20230110_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='conversion',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='sensor',
            name='sampling_rate',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='sensor',
            name='unit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='SensorColumnMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('data_type', models.CharField(blank=True, max_length=100)),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='sensormodel.sensor')),
            ],
        ),
    ]
