# Generated by Django 3.2.14 on 2023-02-08 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensormodel', '0014_auto_20230131_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensortype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensormodel.sensortype'),
        ),
    ]
