# Generated by Django 3.2.16 on 2023-04-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensormodel', '0015_alter_sensor_sensortype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensortype',
            name='sensor_id_row',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='sensortype',
            name='sensortype',
            field=models.CharField(choices=[('I', 'IMU'), ('C', 'Camera'), ('M', 'Microphone')], default=1, max_length=1),
        ),
    ]
