# Generated by Django 3.2.16 on 2023-05-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensormodel', '0016_auto_20230406_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensortype',
            name='timezone',
            field=models.TextField(default='UTC'),
        ),
        migrations.AlterField(
            model_name='sensortype',
            name='sensortype',
            field=models.CharField(choices=[('I', 'IMU'), ('C', 'Camera'), ('M', 'Microphone')], default='I', max_length=1),
        ),
    ]
