# Generated by Django 3.2.16 on 2023-07-11 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_projectimport'),
        ('sensormodel', '0018_auto_20230704_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
