# Generated by Django 3.1.14 on 2023-11-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensormodel', '0019_auto_20230927_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='description',
        ),
        migrations.AddField(
            model_name='sensor',
            name='name',
            field=models.TextField(blank=True, max_length=25),
        ),
    ]
