# Generated by Django 3.1.14 on 2023-11-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensormodel', '0020_auto_20231107_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='sensor_id',
            new_name='parsable_sensor_id',
        ),
    ]
