# Generated by Django 3.1.14 on 2023-11-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensormodel', '0021_auto_20231108_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.TextField(max_length=25),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='parsable_sensor_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
