# Generated by Django 3.1.14 on 2023-11-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensormodel', '0023_auto_20231110_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='manual_offset',
            field=models.IntegerField(default=0),
        ),
    ]
