# Generated by Django 3.2.14 on 2023-01-31 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensormodel', '0014_auto_20230131_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FilePathField()),
                ('begin_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('file_hash', models.CharField(blank=True, max_length=10)),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensormodel.sensor')),
            ],
        ),
    ]
