# Generated by Django 3.2.14 on 2023-01-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='begin_datetime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='end_datetime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='file_path',
            field=models.FilePathField(default=''),
        ),
    ]
