# Generated by Django 3.2.14 on 2023-02-07 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensormodel', '0014_auto_20230131_1306'),
        ('sensordata', '0002_auto_20230131_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='begin_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='file_hash',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='file_path',
            field=models.FilePathField(),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sensormodel.sensor'),
        ),
    ]
