# Generated by Django 3.2.14 on 2023-02-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0003_auto_20230207_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='file_path',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='sensordata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
