# Generated by Django 3.2.14 on 2023-02-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0004_auto_20230207_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
