# Generated by Django 3.2.16 on 2023-04-06 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensormodel', '0016_auto_20230406_1354'),
        ('sensordata', '0005_sensordata_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorOffset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.IntegerField(blank=True, null=True)),
                ('offset_Date', models.DateTimeField(blank=True, null=True)),
                ('sensor_A', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SensorA_offsets', to='sensormodel.sensor')),
                ('sensor_B', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SensorB_offsets', to='sensormodel.sensor')),
            ],
        ),
    ]
