# Generated by Django 3.2.16 on 2023-05-25 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensormodel', '0017_auto_20230525_2133'),
        ('sensordata', '0006_sensoroffset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='sensordata',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='sensortype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sensormodel.sensortype'),
        ),
    ]
