# Generated by Django 3.2.16 on 2023-07-04 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensormodel', '0018_auto_20230704_1245'),
        ('sensordata', '0007_auto_20230525_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='sensortype',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sensormodel.sensor'),
        ),
    ]
