# Generated by Django 3.2.16 on 2023-07-21 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_projectimport'),
        ('sensordata', '0008_auto_20230704_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='project_id',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
