# Generated by Django 3.2.16 on 2023-09-17 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensormodel', '0019_deployment_project'),
        ('sensordata', '0010_auto_20230726_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensoroffset',
            name='camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Camera_offsets', to='sensormodel.sensor'),
        ),
        migrations.AlterField(
            model_name='sensoroffset',
            name='imu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Imu_offsets', to='sensormodel.sensor'),
        ),
    ]
