# Generated by Django 3.1.14 on 2023-10-26 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20220211_2218'),
        ('data_import', '0002_auto_20231005_1606'),
        ('sensordata', '0010_auto_20231026_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='file_upload_project2',
        ),
        migrations.AddField(
            model_name='sensoroffset',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='file_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_import.fileupload'),
        ),
    ]
