# Generated by Django 3.2.16 on 2023-09-20 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensormodel', '0020_auto_20230917_1403'),
        ('sensordata', '0011_auto_20230917_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensoroffset',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='sensoroffset',
            name='imu',
        ),
        migrations.AddField(
            model_name='sensoroffset',
            name='sensor_A',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SensorA_offsets', to='sensormodel.sensor'),
        ),
        migrations.AddField(
            model_name='sensoroffset',
            name='sensor_B',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SensorB_offsets', to='sensormodel.sensor'),
        ),
    ]
