# Generated by Django 3.1.14 on 2023-11-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0013_remove_sensordata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
