template: "Mandatory field" #https://github.com/release-drafter/release-drafter/blob/master/bin/generate-schema.js#L16
autolabeler:
  - label: 'build'
    title:
      - '/^build:/'
  - label: 'fix'
    title:
      - '/^fix:/'
  - label: 'feat'
    title:
      - '/^feat:/'
  - label: 'docs'
    title:
      - '/^docs:/'
  - label: 'chore'
    title:
      - '/^chore:/'
      - '/^chore(deps):/'
      - '/^chore(deps-dev):/'
      - '/^build(deps):/'
      - '/^build(deps-dev):/'
  - label: 'ci'
    title:
      - '/^ci:/'
  - label: 'perf'
    title:
      - '/^perf:/'
  - label: 'refactor'
    title:
      - '/^refactor:/'
  - label: 'revert'
    title:
      - '/^revert:/'
  - label: 'style'
    title:
      - '/^style:/'
  - label: 'test'
    title:
      - '/^test:/'