title: 命名实体识别
type: community
group: 自然语言处理
order: 3
image: /static/templates/named-entity-recognition.png
details: <h1>从文本中提取命名实体</h1>
config: |
  <View>
    <Labels name="label" toName="text">
      <Label value="PER" background="red"/>
      <Label value="ORG" background="darkorange"/>
      <Label value="LOC" background="orange"/>
      <Label value="MISC" background="green"/>
    </Labels>

    <Text name="text" value="$text"/>
  </View>

