default_stages: [ manual ]
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.9
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: local
    hooks:
      - id: biome-check
        name: biome-check
        entry: bash -c 'cd web && yarn biome check . --write --diagnostic-level=error'
        language: system
        pass_filenames: false
        files: ^web/.*
