default_stages: [pre-push]
repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.285
    hooks:
      - id: ruff
        args: [ --fix, --show-fixes, --exit-non-zero-on-fix ]
-   repo: https://github.com/grantjenks/blue
    rev: v0.9.1
    hooks:
      - id: blue
        args: [ --check, --diff, --color ]
