default_stages: [ manual ]
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.285
    hooks:
      - id: ruff
        args: [ --fix, --show-fixes ]
  - repo: https://github.com/grantjenks/blue
    rev: v0.9.1
    hooks:
      - id: blue
  - repo: https://github.com/biomejs/pre-commit
    rev: "v0.1.0"
    hooks:
      - id: biome-check
        args: [ --config-path, ./web ]
        additional_dependencies: [ "@biomejs/biome@1.7.1" ]
        files: ^web/.*
  - repo: local
    hooks:
      - id: stylelint
        name: stylelint
        entry: bash -c 'cd web && npx stylelint **/*.scss --fix'
        language: node
        types: [ scss ]
        files: ^.*\.scss$
