language: node_js

branches:
  only:
    - master
    - /^release\/.+$/
    - /^major\/.+$/

node_js:
  - node

cache:
  directories:
    - node_modules

script:
  - npm test
  - unset CI
  - npm run publish
