# Generated by Django 3.1.14 on 2022-01-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='labellink',
            constraint=models.UniqueConstraint(fields=('project', 'label'), name='unique_label_project'),
        ),
    ]
