# Generated by Django 3.2.16 on 2023-03-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels_manager', '0003_auto_20221005_1620'),
        ('labels_manager', '0003_auto_20221213_1612'),
    ]

    operations = [
    ]
