# Generated by Django 3.2.24 on 2024-05-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0005_auto_20240319_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelinterface',
            name='base_model',
            field=models.TextField(blank=True, default='gpt-3.5-turbo', help_text='Base model used by this model (Like gpt-3.5-turbo)', null=True, verbose_name='base model'),
        ),
    ]
