# Generated by Django 3.2.25 on 2024-06-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0007_auto_20240617_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrun',
            name='total_tasks',
            field=models.IntegerField(default=0, verbose_name='total tasks'),
        ),
    ]
