# Generated by Django 3.2.25 on 2024-08-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0009_alter_thirdpartymodelversion_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelinterface',
            name='skill_name',
            field=models.CharField(choices=[('TextClassification', 'TextClassification'), ('NamedEntityRecognition', 'NamedEntityRecognition')], default='TextClassification', max_length=255),
        ),
    ]
