# Generated by Django 4.2.15 on 2024-08-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml_models", "0009_alter_thirdpartymodelversion_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelinterface",
            name="skill_name",
            field=models.CharField(
                choices=[
                    ("TextClassification", "TextClassification"),
                    ("NamedEntityRecognition", "NamedEntityRecognition"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        # set existing ModelInterface objects to text classification
        migrations.RunSQL(
            sql=[
                "ALTER TABLE ml_models_modelinterface ALTER COLUMN skill_name SET DEFAULT 'TextClassification';",
            ],
            reverse_sql=[
                "ALTER TABLE ml_models_modelinterface ALTER COLUMN skill_name DROP DEFAULT;",
            ]
        ),
    ]
