# Generated by Django 3.2.25 on 2024-08-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0010_modelinterface_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdpartymodelversion',
            name='provider',
            field=models.CharField(choices=[('OpenAI', 'OpenAI'), ('AzureOpenAI', 'AzureOpenAI'), ('Custom', 'Custom')], default='OpenAI', help_text='The model provider to use e.g. OpenAI', max_length=255),
        ),
    ]
