# Generated by Django 5.1.15 on 2026-04-10 10:20

import django.db.models.deletion
import django_migration_linter as linter
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml_models", "0016_alter_thirdpartymodelversion_provider"),
        ("tasks", "0062_task_data_trgm_idx_async"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.AddField(
            model_name="modelrun",
            name="filters_json",
            field=models.JSONField(
                blank=True,
                help_text="DM filter group for Filtered subset. Stored for display/re-run purposes.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="modelrun",
            name="sample_subset_size",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Custom sample size for Sample subset. Uses PROMPTER_SAMPLE_SUBSET_SIZE if not set.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="modelrun",
            name="source_model_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="re_evaluations",
                to="ml_models.modelrun",
            ),
        ),
        migrations.AddField(
            model_name="modelrun",
            name="task_ids",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="List of task IDs for Custom subset re-evaluation.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="thirdpartymodelversion",
            name="max_few_shot_examples",
            field=models.PositiveIntegerField(
                blank=True,
                db_default=0,
                help_text="Max number of few-shot examples to include in prompts. 0 = disabled.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="modelrun",
            name="project_subset",
            field=models.CharField(
                choices=[
                    ("All", "All"),
                    ("HasGT", "HasGT"),
                    ("Sample", "Sample"),
                    ("Custom", "Custom"),
                ],
                default="HasGT",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="modelrun",
            name="total_correct_predictions",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="total correct predictions",
            ),
        ),
        migrations.AlterField(
            model_name="modelrun",
            name="total_predictions",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="total predictions"
            ),
        ),
        migrations.AlterField(
            model_name="modelrun",
            name="total_tasks",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="total tasks"
            ),
        ),
        migrations.CreateModel(
            name="FewShotExample",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "annotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="few_shot_usages",
                        to="tasks.annotation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="few_shot_examples",
                        to="ml_models.thirdpartymodelversion",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="few_shot_usages",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("model_version", "task", "annotation")},
            },
        ),
    ]
