title: 意图分类和槽填充
type: community
group: 对话式人工智能
image: /static/templates/intent-classification-and-slot-filling.png
details: <h1>通过选择对话意图和提取槽实体来构建面向任务的对话系统</h1>
config: |
  <View>
    <ParagraphLabels name="entity_slot" toName="dialogue">
      <Label value="Person" />
      <Label value="Organization" />
      <Label value="Location" />
      <Label value="Datetime" />
      <Label value="Quantity" />
    </ParagraphLabels>
    <Paragraphs name="dialogue" value="$humanMachineDialogue" layout="dialogue" />
      <Choices name="intent" toName="dialogue"
           choice="single" showInLine="true">
          <Choice value="Greeting"/>
          <Choice value="Customer request"/>
          <Choice value="Small talk"/>
      </Choices>
  </View>

