name: Setup frontend environment
description: Setup frontend environment

inputs:
  node-version:
    description: node version
    default: "22"
    required: false
  directory:
    description: frontend directory
    default: "web"
    required: false

runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: "${{ inputs.node-version }}"

    - name: Setup bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: "${{ inputs.directory }}/package.json"

    - name: Cache node_modules
      uses: actions/cache@v4
      id: node-modules-cache
      with:
        path: |
          ${{ inputs.directory }}/node_modules
          !${{ inputs.directory }}/node_modules/.cache
        key: ${{ runner.os }}-node-${{ inputs.node-version }}-node-modules-v4-${{ hashFiles(format('{0}/bun.lock', inputs.directory)) }}

    - name: Configure bun cache
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-node-${{ inputs.node-version }}-bun-v1-${{ hashFiles(format('{0}/bun.lock', inputs.directory)) }}
        restore-keys: |
          ${{ runner.os }}-node-${{ inputs.node-version }}-bun-v1-

    - name: Install dependencies
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      working-directory: "${{ inputs.directory }}"
      shell: bash
      run: bun install --frozen-lockfile

    - name: Print node_modules size
      shell: bash
      run: du -d 0 -h ${{ inputs.directory }}/node_modules
