# Generated by Django 3.2.25 on 2024-07-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0010_auto_20230718_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='view',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='view',
            name='order',
            field=models.IntegerField(default=0, help_text='Order of view', verbose_name='order'),
        ),
    ]
