# Generated by Django 3.2.25 on 2024-07-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0011_auto_20240711_1236'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='view',
            index=models.Index(fields=['project', 'order'], name='data_manage_project_69b96e_idx'),
        ),
    ]
