[mypy]
# 플러그인 활성화
plugins =
    mypy_django_plugin.main,
    mypy_drf_plugin.main

# 오류 무시 설정 (필수 아님, 편의상 추천)
ignore_missing_imports = True
strict_optional = True

[mypy.plugins.django-stubs]
# 여기에 프로젝트의 settings 경로를 적어주세요!
django_settings_module = core.settings.label_studio