# Generated by Django 5.1.15 on 2025-12-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fsm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotationstate",
            name="state",
            field=models.CharField(
                choices=[("CREATED", "Created"), ("COMPLETED", "Completed")],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
