# Generated by Django 5.1.15 on 2026-01-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fsm", "0002_alter_annotationstate_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotationstate",
            name="state",
            field=models.CharField(
                choices=[("CREATED", "Created")], db_index=True, max_length=50
            ),
        ),
    ]
