import i18next from "i18next";

/**
 * Display-side mapping for system titles generated by the Django data manager
 * (column titles and action registry titles). They arrive as English data on
 * the API, so we translate the known fixed set at render time; anything
 * user-defined (data columns, custom tabs) passes through untouched.
 */

const COLUMN_TITLES: Record<string, string> = {
  ID: "dataManager:colId",
  "Inner ID": "dataManager:colInnerId",
  Completed: "dataManager:colCompleted",
  Annotations: "dataManager:colAnnotations",
  Cancelled: "dataManager:colCancelled",
  Predictions: "dataManager:colPredictions",
  "Annotated by": "dataManager:colAnnotatedBy",
  "Annotation results": "dataManager:colAnnotationResults",
  "Annotation IDs": "dataManager:colAnnotationIds",
  "Prediction score": "dataManager:colPredictionScore",
  "Prediction model versions": "dataManager:colPredictionModelVersions",
  "Prediction results": "dataManager:colPredictionResults",
  "Upload filename": "dataManager:colUploadFilename",
  "Storage filename": "dataManager:colStorageFilename",
  "Created at": "dataManager:colCreatedAt",
  "Updated at": "dataManager:colUpdatedAt",
  "Updated by": "dataManager:colUpdatedBy",
  "Lead Time": "dataManager:colLeadTime",
  Drafts: "dataManager:colDrafts",
  data: "dataManager:colData",
};

const ACTION_TITLES: Record<string, string> = {
  "Delete Tasks": "dataManager:actDeleteTasks",
  "Delete Annotations": "dataManager:actDeleteAnnotations",
  "Delete Predictions": "dataManager:actDeletePredictions",
  "Create Annotations From Predictions": "dataManager:actCreateAnnotationsFromPredictions",
  "Retrieve Predictions": "dataManager:actRetrievePredictions",
  "Rename Labels": "dataManager:actRenameLabels",
  "Cache Labels": "dataManager:actCacheLabels",
  "Propagate Annotations": "dataManager:actPropagateAnnotations",
  "Remove Duplicated Tasks": "dataManager:actRemoveDuplicatedTasks",
  "Generate Next Task": "dataManager:actGenerateNextTask",
  "Add or Update Columns": "dataManager:actAddOrUpdateColumns",
};

export function translateColumnTitle(title: string | null | undefined): string {
  if (!title) return title ?? "";
  const key = COLUMN_TITLES[title];
  return key ? i18next.t(key) : title;
}

export function translateActionTitle(title: string | null | undefined): string {
  if (!title) return title ?? "";
  const key = ACTION_TITLES[title];
  return key ? i18next.t(key) : title;
}
