# Generated by Django 5.1.15 on 2026-07-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0004_auto_20221221_1101"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhook",
            name="consecutive_failures",
            field=models.PositiveIntegerField(
                db_default=0,
                default=0,
                help_text="Number of consecutive failed deliveries; the webhook auto-disables at the configured threshold",
                null=True,
                verbose_name="consecutive failures",
            ),
        ),
    ]
