STALE_FEATURE_FLAGS = {
    'fflag_feat_front_optic_66_lazy_chart_evaluation_19092023_short': False,
    'fflag_fix_front_lsdv_4600_lead_time_27072023_short': False,
    'ff_back_dev_4664_remove_storage_file_on_export_delete_29032023_short': False,
    'fflag_feat_front_dev_3873_labeling_ui_improvements_short': True,
    'fflag_feat_back_dev_3756_queue_enrollment_min_short': False,
    'fflag_fix_front_lsdv_4620_memory_leaks_100723_short': False,
    # Jan 16
    'fflag_feat_all_lsdv_e_295_project_level_roles_via_saml_scim_ldap_short': True,
    'ff_back_2884_comments_notifications_02092022_short': True,
    'ff_front_dev_1480_created_on_in_review_180122_short': True,
    'fflag_fix_front_leap_32_zoom_perf_190923_short': True,
    'fflag_feat_front_lsdv_5452_taxonomy_labeling_110823_short': True,
    # Feb 5
    'fflag_feature_all_optic_1421_cold_start_v2': False,
    'fflag_fix_back_optic_1407_optimize_tasks_api_pagination_counts': True,
    'fflag_fix_optic_1259_lse_projects_read_apis_use_replica_short': True,
    'fflag_feat_optic_1025_zendesk_widget_integration': False,
    'fflag_feat_optic_378_limit_projects_per_page_to_ten_short': True,
    # Feb 6
    'fflag_feat_all_dia_1576_prompts_easy_breezy_onboarding_short_async_presets_ks': False,
    'fflag_front_dia_1150_ddisco_sneak_preview': False,
    # Feb 25
    'fflag_feat_front_leap_1198_unsaved_changes_180724': True,
    'fflag_fix_leap_246_multi_object_hotkeys_160124_short': True,
    'fflag_fix_leap_466_text_sanitization': True,
    # Dec 29
    'fflag_feat_all_optic_1811_automax_project_setup_streaming': True,
    'fflag_feat_all_leap_1682_plugins_v0': True,
    # Dec 31
    'fflag_root_43_prediction_results_filter': True,
    'fflag_root_45_better_user_filter': True,
    'fflag_root_13_annotation_results_filtering': True,
    'fflag_feat_root_16_support_parquet_cloud_storage': True,
    'fflag_feat_root_11_support_jsonl_cloud_storage': True,
    'fflag_feat_root_47_plugins_without_eval': False,
    'fflag_feat_front_bros_327_multiple_labels_regions_short': True,
    'fflag_feat_front_bros_199_enable_select_all_in_ner_phrase_short': True,
    'fflag_fix_leap_2052_detect_empty_filters_at_next_task_endpoint_short': True,
    'fflag_feat_dia_1925_view_sample_raw_json_short': False,
    'fflag__feature_develop__prompts__dia_1868_azure_ai_foundry': True,
    'fflag_fix_back_leap_1818_set_convert_background_failure_logging_02062025_short': True,
    'fflag_feat_all_leap_1732_pausing_an_annotator_short': True,
    'fflag_feat_all_leap_1429_flexible_reject_mode_250924_short': True,
    'fflag_fix_front_lsdv_4998_missed_dynamic_children_030523_short': True,
    'fflag_fix_back_lsdv_4929_limit_exports_10042023_short': True,
    'fflag_fix_front_dev_3377_image_regions_shift_on_resize_280922_short': True,
    # Jan 5
    'fflag_feat_all_fit_524_review_time_chart': True,
    'fflag_feat_523_emitting_task_events_for_annotation_and_review': True,
    'fflag_feat_all_fit_162_workspaces_projects_ui_improvements': True,
    'fflag_feat_front_fit_183_email_notifications_short': True,
    'fflag_fix_back_optic_1380_dashboard_task_chart_grouped_by_completed_at_reviewed_at_short': True,
    'fflag_feat_front_optic_1746_improve_global_error_messages_short': True,
    'ff_front_optic_1610_ask_ai_questions': True,
    'fflag_fix_front_optic_1608_improve_video_frame_seek_precision_short': True,
    'fflag_feat_front_optic_1479_improve_image_tag_memory_usage_short': True,
    'ff_front_optic_1494_saved_templates_to_custom_templates': True,
    'fflag_feat_all_optic_1354_sum_annotation_region_count_short': True,
    'fflag_feat_front_optic_1217_theme_toggle_short': True,
    'feat_optic_1098_annotation_history_lead_time_charts': True,
    'fflag_feat_back_optic_428_scim_multi_mapping': True,
}
