# Generated by Django 3.2.25 on 2024-08-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model_providers', '0002_auto_20240722_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelproviderconnection',
            name='cached_available_models',
            field=models.CharField(blank=True, help_text='List of available models from the provider', max_length=4096, null=True),
        ),
    ]
