# Generated by Django 4.2.15 on 2024-09-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model_providers', '0003_modelproviderconnection_cached_available_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelproviderconnection',
            name='cached_available_models',
            field=models.TextField(blank=True, help_text='List of available models from the provider', null=True),
        ),
    ]
