title: Video Timeline Segmentation
type: community
group: Videos
image: /static/templates/video-timeline-segmentation.png
details: <h1>Select and classify video segments</h1>
config: |
  <View>
    <Header value="Video timeline segmentation via AudioPlus sync trick"/>
    <Video name="video" value="$video" sync="audio"/>
    <Labels name="tricks" toName="audio" choice="multiple">
      <Label value="Kickflip" background="#1BB500" />
      <Label value="360 Flip" background="#FFA91D" />
      <Label value="Trick" background="#358EF3" />
    </Labels>
    <AudioPlus name="audio" value="$video" sync="video" speed="false"/>
  </View>

  <!--
    Audio tag uses the same $video file to be in sync, video is muted
  -->

  <!-- {
   "video": "/static/samples/opossum_snow.mp4"
  } -->

