title: 声音事件检测
type: community
group: 音频/语音处理
image: /static/templates/sound-event-detection.png
details: <h1>选择音频跨度并对声音事件进行分类</h1>
config: |
  <View>
    <Labels name="label" toName="audio" zoom="true" hotkey="ctrl+enter">
      <Label value="Event A" background="red"/>
      <Label value="Event B" background="green"/>
    </Labels>
    <AudioPlus name="audio" value="$audio"/>
  </View>

