# Generated by Django 5.1.13 on 2025-10-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jwtsettings",
            name="api_tokens_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable JWT API token authentication for this organization",
                verbose_name="JWT API tokens enabled",
            ),
        ),
        migrations.AlterField(
            model_name="jwtsettings",
            name="legacy_api_tokens_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable legacy API token authentication for this organization",
                verbose_name="legacy API tokens enabled",
            ),
        ),
    ]
