#!/bin/bash

cat /etc/os-release
lsb_release -a

echo "=> Current dir:"
echo $PWD

echo "=> Install python"
apt update
apt -y install software-properties-common
add-apt-repository ppa:deadsnakes/ppa
apt update
apt -y install python3.7 python3-pip

echo "=> Environmental setup:"
which python3
which python3.7
python3 --version
python3.7 --version
env

echo "=> Update links"
update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 2
python3 --version

echo "=> Upgrade pip"
pip3 --version
pip3 install --upgrade pip
pip3 --version

echo "=> Install prerequisites..."
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
source ~/.bashrc
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
nvm install node
nvm use node
apt install unzip


echo "npm version:"
npm -v
echo "node version:"
node -v
echo "unzip version:"
unzip -v

echo "=> Installing npm packages..."
npm i node-fetch

echo "=> Installing environment..."
pip3 install -e .

echo "=> Run image prebuild..."
./deploy/prebuild.sh
