#!/bin/bash

cat /etc/os-release
lsb_release -a

echo "=> Current dir:"
echo $PWD

echo "=> Install python"
sudo apt update
sudo apt install software-properties-common
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update
sudo apt install python3.7
alias python3=python3.7

echo "=> Environmental setup:"
env
python3 --version

echo "=> Install prerequisites..."
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
source ~/.bashrc
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
nvm install node
nvm use node
apt install unzip


echo "npm version:"
npm -v
echo "node version:"
node -v
echo "unzip version:"
unzip -v

echo "=> Installing npm packages..."
npm i node-fetch

echo "=> Installing environment..."
pip3 install --upgrade pip
pip3 install -e .

echo "=> Run image prebuild..."
./deploy/prebuild.sh
