# Generated by Django 3.2.16 on 2023-07-04 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_import', '0002_alter_fileupload_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('start_time', models.FloatField(blank=True, null=True)),
                ('end_time', models.FloatField(blank=True, null=True)),
                ('file_upload', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_import.fileupload')),
            ],
        ),
    ]
