# Generated by Django 3.2.16 on 2023-07-11 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensormodel', '0019_deployment_project'),
        ('projects', '0022_projectimport'),
        ('subjectannotation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectpresence',
            name='project_id',
        ),
        migrations.AddField(
            model_name='subjectpresence',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='subjectpresence',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensormodel.subject'),
        ),
    ]
