# Generated by Django 3.1.12 on 2021-09-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20210517_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='show_ground_truth_first',
            field=models.BooleanField(default=False, verbose_name='show ground truth first'),
        ),
        migrations.AlterField(
            model_name='project',
            name='show_overlap_first',
            field=models.BooleanField(default=False, verbose_name='show overlap first'),
        ),
    ]
