# Generated by Django 3.1.13 on 2021-11-29 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_skip_queue'),
        ('projects', '0013_project_reveal_preannotations_interactively'),
    ]

    operations = [
    ]
