# Generated by Django 3.1.14 on 2022-01-17 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_parsed_label_config'),
        ('projects', '0013_project_skip_queue'),
    ]

    operations = [
    ]
