# Generated by Django 3.1.14 on 2022-01-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_merge_20220117_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show_data_manager_to_reviewers',
            field=models.BooleanField(default=False, help_text='Show data manager to annotator', verbose_name='show data manager to reviewers'),
        ),
    ]
