# Generated by Django 3.2.16 on 2023-02-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_project_control_weights'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['pinned_at', 'created_at'], name='project_pinned__a39ccb_idx'),
        ),
    ]
