# Generated by Django 3.2.16 on 2023-02-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_labelstreamhistory'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='labelstreamhistory',
            constraint=models.UniqueConstraint(fields=('user', 'project'), name='unique_history'),
        ),
    ]
