# Generated by Django 3.2.16 on 2023-02-15 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_labelstreamhistory_unique_history'),
    ]

    operations = [
    ]
