# Generated by Django 3.2.16 on 2023-04-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_merge_20230215_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsummary',
            name='created_labels_drafts',
            field=models.JSONField(default=dict, help_text='Unique drafts labels', null=True, verbose_name='created labels in drafts'),
        ),
    ]
