# Generated by Django 3.2.16 on 2023-05-12 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_projectimport'),
        ('projects', '0022_projectsummary_created_labels_drafts'),
    ]

    operations = [
    ]
