# Generated by Django 3.2.16 on 2023-07-04 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_merge_20230512_1333'),
        ('projects', '0023_projectreimport'),
    ]

    operations = [
    ]
