# Generated by Django 3.2.16 on 2023-08-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_projectsummary_created_labels_drafts'),
        ('projects', '0023_projectreimport'),
    ]

    operations = [
    ]
