# Generated by Django 3.2.20 on 2023-09-21 15:41

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_merge_0023_merge_20230512_1333_0023_projectreimport'),

    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='label_config_hash',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
