# Generated by Django 3.2.25 on 2024-05-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20231103_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='maximum_annotations',
            field=models.IntegerField(default=3, help_text='Maximum number of annotations for one task. If the number of annotations per task is equal or greater to this value, the task is completed (is_labeled=True)', verbose_name='maximum annotation number'),
        ),
    ]
