# Generated by Django 5.1.10 on 2025-12-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0029_alter_project_label_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="label_config",
            field=models.TextField(
                blank=True,
                default='<View>\n  <Image name="image" value="$image" zoom="true"/>\n  <!-- Smart Keypoint Labels (tag3) -->\n  <Header value="Interact: Keypoint Labels"/>\n  <KeyPointLabels name="tag3" toName="image" smart="true">\n    <Label value="Object" smart="true" background="#0000FF"/>\n  </KeyPointLabels>\n     \n   <!-- Smart Rectangle Labels (tag4) -->\n   <Header value="Interact: Rectangle Labels"/>\n   <RectangleLabels name="tag4" toName="image" smart="true">\n     <Label value="Object" smart="true" background="#0000FF"/>\n   </RectangleLabels>\n  \n    <TextArea name="mean_intensity" toName="image"\n            perRegion="true"\n            required="true"\n            maxSubmissions="1"\n            rows="5"\n            placeholder="Mean Intensity (gray/R/G/B; gray=0 on RGB, R/G/B=0 on gray)"\n            displayMode="region-list"\n            />\n  <!-- Brush Labels (tag1) -->\n  <Header value="Result: Brush Labels"/>\n  <BrushLabels name="tag1" toName="image">\n    <Label value="Object" background="#FF0000"/>\n  </BrushLabels>\n  \n  <!-- Polygon Labels (tag2) -->\n  <Header value="Result: Outline"/>\n  <PolygonLabels name="tag2" toName="image">\n    <Label value="Object" background="#00FF00"/>\n  </PolygonLabels>\n</View>',
                help_text="Label config in XML format. See more about it in documentation",
                null=True,
                verbose_name="label config",
            ),
        ),
    ]
