# Generated by Django 5.1.12 on 2025-10-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0030_project_search_vector_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="show_ground_truth_first",
            field=models.BooleanField(
                default=False,
                help_text="Onboarding mode (true): show ground truth tasks first in the labeling stream",
                verbose_name="show ground truth first",
            ),
        ),
    ]
