# Generated by Django 5.1.12 on 2025-10-25 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_alter_organizationmember_deleted_at"),
        ("projects", "0031_alter_project_show_ground_truth_first"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="deleted at"),
        ),
        migrations.AddField(
            model_name="project",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_projects",
                db_index=False,
                to=settings.AUTH_USER_MODEL,
                verbose_name="deleted by",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="purge_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="purge at"),
        ),
    ]
