# Generated by Django 5.1.14 on 2025-11-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0033_projects_soft_delete_indexes_async"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="show_ground_truth_always",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="When enabled, ground truth tasks will be shown to all annotators regardless of overlap",
                verbose_name="show ground truth always",
            ),
        ),
    ]
