# Generated by Django 5.1.14 on 2025-11-27 21:06

from django.db import migrations, models

def set_defaults_based_on_mode(apps, schema_editor):
    """
    For existing projects with show_ground_truth_first=True (Onboarding mode),
    set show_ground_truth_always=True.
    """
    Project = apps.get_model("projects", "Project")
    Project.objects.filter(show_ground_truth_first=True).update(show_ground_truth_always=True)

class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0033_projects_soft_delete_indexes_async"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="show_ground_truth_always",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, ground truth tasks will be shown to all annotators regardless of overlap",
                null=True,
                verbose_name="show ground truth always",
            ),
        ),
        migrations.RunPython(set_defaults_based_on_mode, reverse_code=migrations.RunPython.noop),
    ]
