title: 变化点检测
type: community
group: 时间序列分析
image: /static/templates/change-point-detection.png
details: <h1>识别时间序列信号的变化点</h1>
config: |
  <View>
      <!-- Control tag for region labels -->
      <TimeSeriesLabels name="label" toName="ts">
          <Label value="Change" background="red" />
      </TimeSeriesLabels>

      <!-- Object tag for time series data source -->
      <TimeSeries name="ts" valueType="url" value="$csv"
                  sep=","
                  timeColumn="time"
                  timeFormat="%Y-%m-%d %H:%M:%S.%f"
                  timeDisplayFormat="%Y-%m-%d"
                  overviewChannels="velocity">

          <Channel column="velocity"
                   units="miles/h"
                   displayFormat=",.1f"
                   strokeColor="#1f77b4"
                   legend="Velocity"/>
      </TimeSeries>
  </View>

