# Generated by Django 3.2.16 on 2023-05-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_allow_newsletters'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='boss_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='BossID'),
        ),
        migrations.AddField(
            model_name='user',
            name='ding_user_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='钉钉UserID'),
        ),
    ]
