# Generated by Django 3.2.16 on 2022-11-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_allow_newsletters'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity_per_org',
            field=models.JSONField(default=dict, verbose_name='last activity per org'),
        ),
    ]
