# Generated by Django 3.2.16 on 2023-05-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20230519_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('test1', '菜单 Dashboard'), ('test2', '菜单 Dashboard')),
                'managed': True,
            },
        ),
    ]
