# Generated by Django 3.2.20 on 2023-10-04 23:35

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
