# Generated by Django 3.2.23 on 2024-01-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20231201_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_hotkeys',
            field=models.JSONField(default=dict, help_text='Custom hotkeys', null=True, verbose_name='hotkeys'),
        ),
    ]
