# Generated by Django 3.2.25 on 2024-05-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20240502_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.CharField(blank=True, max_length=1024, verbose_name='roles'),
        ),
    ]
