# Generated by Django 3.1.12 on 2021-07-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('io_storages', '0003_localfilesimportstorage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcsstoragemixin',
            name='google_application_credentials',
            field=models.TextField(blank=True, help_text='The content of GOOGLE_APPLICATION_CREDENTIALS json file', null=True, verbose_name='google_application_credentials'),
        ),
    ]
