# Generated by Django 3.1.13 on 2021-11-23 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('io_storages', '0008_auto_20211122_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azureblobexportstorage',
            name='export_type',
            field=models.CharField(choices=[('task', 'Task'), ('annotation', 'Annotation')], default='task', help_text='Export task or annotation', max_length=128, verbose_name='export type'),
        ),
        migrations.AlterField(
            model_name='gcsexportstorage',
            name='export_type',
            field=models.CharField(choices=[('task', 'Task'), ('annotation', 'Annotation')], default='task', help_text='Export task or annotation', max_length=128, verbose_name='export type'),
        ),
        migrations.AlterField(
            model_name='localfilesexportstorage',
            name='export_type',
            field=models.CharField(choices=[('task', 'Task'), ('annotation', 'Annotation')], default='task', help_text='Export task or annotation', max_length=128, verbose_name='export type'),
        ),
        migrations.AlterField(
            model_name='redisexportstorage',
            name='export_type',
            field=models.CharField(choices=[('task', 'Task'), ('annotation', 'Annotation')], default='task', help_text='Export task or annotation', max_length=128, verbose_name='export type'),
        ),
        migrations.AlterField(
            model_name='s3exportstorage',
            name='export_type',
            field=models.CharField(choices=[('task', 'Task'), ('annotation', 'Annotation')], default='task', help_text='Export task or annotation', max_length=128, verbose_name='export type'),
        ),
    ]
