# Generated by Django 3.1.13 on 2021-12-23 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('io_storages', '0008_auto_20211129_1132'),
        ('io_storages', '0009_auto_20211123_1312'),
    ]

    operations = [
    ]
