# Generated by Django 3.2.16 on 2023-05-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('io_storages', '0012_ossexportstorage_ossexportstoragelink_ossimportstorage_ossimportstoragelink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ossimportstorage',
            name='oss_session_token',
        ),
    ]
