# Generated by Django 3.2.25 on 2024-05-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('io_storages', '0016_add_aws_sse_kms_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='azureblobstoragemixin',
            name='account_client_id',
            field=models.TextField(blank=True, help_text='Azure Blob account client id', null=True, verbose_name='account_client_id'),
        ),
        migrations.AddField(
            model_name='azureblobstoragemixin',
            name='account_client_secret',
            field=models.TextField(blank=True, help_text='Azure Blob client secret', null=True, verbose_name='account_client_secret'),
        ),
        migrations.AddField(
            model_name='azureblobstoragemixin',
            name='account_tenant_id',
            field=models.TextField(blank=True, help_text='Azure Blob tenant id', null=True, verbose_name='account_tenant_id'),
        ),
    ]
