# Generated by Django 4.2.13 on 2024-08-07 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0026_auto_20231103_0020"),
        ("tasks", "0047_merge_20240318_2210"),
        ("io_storages", "0016_add_aws_sse_kms_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="azureblobexportstorage",
            name="project",
            field=models.ForeignKey(
                help_text="A unique integer value identifying this project.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)ss",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="azureblobexportstoragelink",
            name="annotation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to="tasks.annotation",
            ),
        ),
        migrations.AlterField(
            model_name="azureblobimportstorage",
            name="project",
            field=models.ForeignKey(
                help_text="A unique integer value identifying this project.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)ss",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="azureblobimportstoragelink",
            name="task",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to="tasks.task",
            ),
        ),
        migrations.AlterField(
            model_name="gcsexportstorage",
            name="project",
            field=models.ForeignKey(
                help_text="A unique integer value identifying this project.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)ss",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="gcsexportstoragelink",
            name="annotation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to="tasks.annotation",
            ),
        ),
        migrations.AlterField(
            model_name="gcsimportstorage",
            name="project",
            field=models.ForeignKey(
                help_text="A unique integer value identifying this project.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)ss",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="gcsimportstoragelink",
            name="task",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to="tasks.task",
            ),
        ),
        migrations.AlterField(
            model_name="localfilesexportstorage",
            name="project",
            field=models.ForeignKey(
                help_text="A unique integer value identifying this project.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)ss",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="localfilesexportstoragelink",
            name="annotation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to="tasks.annotation",
            ),
        ),
        migrations.AlterField(
            model_name="localfilesimportstorage",
            name="project",
            field=models.ForeignKey(
                help_text="A unique integer value identifying this project.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)ss",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="localfilesimportstoragelink",
            name="task",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to="tasks.task",
            ),
        ),
        migrations.AlterField(
            model_name="redisexportstorage",
            name="project",
            field=models.ForeignKey(
                help_text="A unique integer value identifying this project.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)ss",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="redisexportstoragelink",
            name="annotation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to="tasks.annotation",
            ),
        ),
        migrations.AlterField(
            model_name="redisimportstorage",
            name="project",
            field=models.ForeignKey(
                help_text="A unique integer value identifying this project.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)ss",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="redisimportstoragelink",
            name="task",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to="tasks.task",
            ),
        ),
        migrations.AlterField(
            model_name="s3exportstorage",
            name="project",
            field=models.ForeignKey(
                help_text="A unique integer value identifying this project.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)ss",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="s3exportstoragelink",
            name="annotation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to="tasks.annotation",
            ),
        ),
        migrations.AlterField(
            model_name="s3importstorage",
            name="project",
            field=models.ForeignKey(
                help_text="A unique integer value identifying this project.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)ss",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="s3importstoragelink",
            name="task",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to="tasks.task",
            ),
        ),
    ]
