# Generated by Django 4.2.13 on 2024-08-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("io_storages", "0017_alter_azureblobexportstorage_project_and_more"),
        ("io_storages", "0017_auto_20240731_1638"),
    ]

    operations = []
