# Generated by Django 3.2.25 on 2024-04-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('io_storages', '0017_azureserviceprincipalexportstorage_azureserviceprincipalexportstoragelink_azureserviceprincipalimpor'),
    ]

    operations = [
        migrations.AddField(
            model_name='azureserviceprincipalstoragemixin',
            name='user_delegation_key',
            field=models.TextField(blank=True, help_text='User Delegation Key (Backend)', null=True, verbose_name='user_delegation_key'),
        ),
    ]
