# Generated by Django 3.2.25 on 2024-07-04 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('io_storages', '0017_auto_20240509_2317'),
        ('io_storages', '0018_azureserviceprincipalstoragemixin_user_delegation_key'),
    ]

    operations = [
    ]
