# Generated by Django 3.2.25 on 2024-07-08 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('io_storages', '0019_merge_20240704_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='azureblobstoragemixin',
            name='account_client_id',
        ),
        migrations.RemoveField(
            model_name='azureblobstoragemixin',
            name='account_client_secret',
        ),
        migrations.RemoveField(
            model_name='azureblobstoragemixin',
            name='account_tenant_id',
        ),
    ]
