# Generated by Django 3.2.20 on 2023-10-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='verify_ssl_certs',
            field=models.BooleanField(blank=True, help_text='organization-level override of settings.VERIFY_SSL_CERTS', null=True, verbose_name='verify ssl certs'),
        ),
    ]
