# Generated by Django 3.2.20 on 2023-11-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organizationmember_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, help_text='Timestamp indicating when the organization member was marked as deleted.  If NULL, the member is not considered deleted.', null=True, verbose_name='deleted at'),
        ),
    ]
