# Generated by Django 3.2.20 on 2023-12-04 17:20

from django.db import migrations
from organizations.models import Organization
from core.models import AsyncMigrationStatus
from core.utils.common import create_hash
from core.redis import start_job_async_or_sync
import logging


def _update_organizations_tokens(migration_name):
    migration = AsyncMigrationStatus.objects.create(
        name=migration_name,
        status=AsyncMigrationStatus.STATUS_STARTED,
    )

    for organization_id in Organization.objects.all().values_list("id", flat=True):
        t = create_hash()
        Organization.objects.filter(id=organization_id).update(token=t)

    migration.status = AsyncMigrationStatus.STATUS_FINISHED
    migration.save()

logger = logging.getLogger(__name__)

def update_organizations_tokens(migration_name):
    logger.info('Start updating organization tokens')
    start_job_async_or_sync(_update_organizations_tokens, migration_name=migration_name)
    logger.info('Finished updating organization tokens')

def forward(apps, schema_editor):
    update_organizations_tokens('0007_auto_20231204_1720')


def backwards(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organizationmember_deleted_at'),
    ]

    operations = [
        migrations.RunPython(forward, backwards)
    ]
