# Generated by Django 3.2.16 on 2023-07-21 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensormodel', '0019_deployment_project'),
        ('projects', '0022_projectimport'),
        ('sensordata', '0009_auto_20230721_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_video', models.FloatField(blank=True, null=True)),
                ('end_video', models.FloatField(blank=True, null=True)),
                ('start_imu', models.FloatField(blank=True, null=True)),
                ('end_imu', models.FloatField(blank=True, null=True)),
                ('imu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imu', to='sensordata.sensordata')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sensormodel.subject')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='sensordata.sensordata')),
            ],
        ),
    ]
