# Generated by Django 3.2.16 on 2023-07-22 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_projectimport'),
        ('sensordata', '0009_auto_20230721_1723'),
        ('sensormodel', '0019_deployment_project'),
        ('taskgeneration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskPair',
            new_name='VideoImuOverlap',
        ),
    ]
