title: Video Classification
type: community
group: Videos
image: /static/templates/video-classification.png
details: <h1>Classify video</h1>
config: |
  <View>
    <HyperText name="video" value="$video"/>
    <Choices name="choice" toName="video" showInLine="true">
      <Choice value="Blurry" />
      <Choice value="Sharp" />
    </Choices>
  </View>

  <!-- {

  "data": {
     "video": "<video src='static/samples/opossum_snow.mp4' width=100% controls>",
     "videoSource": "/static/samples/opossum_snow.mp4"
  },

  "annotations": [{"result":
      [
          {
              "value": {
                  "choices": [
                      "Blurry"
                  ]
              },
              "id": "vB3U85jSU4",
              "from_name": "choice",
              "to_name": "video",
              "type": "choices"
          }
      ]
    }]
  }
  -->
