# Generated by Django 5.1.10 on 2025-12-26 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("djstripe", "0001_initial"),
        ("organizations", "0007_add_joined_via_invitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Stripe customer",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_customers",
                        to="djstripe.customer",
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        help_text="Organization linked to Stripe customer",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stripe_customer",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Customer",
                "verbose_name_plural": "Organization Customers",
                "db_table": "billing_organization_customer",
            },
        ),
    ]
