# Generated by Django 5.1.10 on 2025-12-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeWebhookIngest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stripe_event_id", models.CharField(db_index=True, help_text="Stripe Event ID, e.g. evt_123", max_length=255, unique=True, verbose_name="stripe event id")),
                ("event_type", models.CharField(blank=True, default="", max_length=255, verbose_name="event type")),
                ("livemode", models.BooleanField(default=False, verbose_name="livemode")),
                ("payload", models.JSONField(verbose_name="payload")),
                ("status", models.CharField(choices=[("received", "received"), ("queued", "queued"), ("processed", "processed"), ("failed", "failed")], default="received", max_length=32, verbose_name="status")),
                ("job_id", models.CharField(blank=True, default="", max_length=255, verbose_name="rq job id")),
                ("attempts", models.PositiveIntegerField(default=0, verbose_name="attempts")),
                ("last_error", models.TextField(blank=True, default="", verbose_name="last error")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
            ],
            options={
                "verbose_name": "Stripe Webhook Ingest",
                "verbose_name_plural": "Stripe Webhook Ingests",
                "db_table": "billing_stripe_webhook_ingest",
            },
        ),
    ]





