title: 响应选择
type: community
group: 对话式人工智能
image: /static/templates/response-selection.png
details: <h1>通过选择下一个对话响应来收集聊天机器人训练数据</h1>
config: |
  <View>
    <Paragraphs name="prg" value="$humanMachineDialogue" layout="dialogue" />
    <Header value="Choose response" />
    <View style="display: flex;">
      <View>
      <Text name="resp1" value="$respone" />
      <Text name="resp2" value="$resptwo" />
      <Text name="resp3" value="$respthree" />
      </View>
      <View style="padding: 50px;">
      <Choices name="resp" toName="prg" required="true">
        <Choice value="One" />
        <Choice value="Two" />
        <Choice value="Three" />
      </Choices>
      </View>
    </View>
  </View>

