---
name: Codespell

on:
  push:
    branches: [develop,master]
  pull_request:
    branches: [develop,master]

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: codespell-project/actions-codespell@master
