name: label-studio:tests

on:
  push:
    branches: ['*', '*/*', master]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current commit
      uses: actions/checkout@v2

    - name: Install python
      uses: actions/setup-python@v2
      with: # version doesn't matter because we just run e2e test in here
        python-version: '3.8'

    # Maybe they are identical so better to remove the first redundant one
    - name: Install dependencies
      uses: py-actions/py-dependency-install@v2
    - name: Install dependencies
      run: |
        pip install --upgrade cython
        pip install -e .

    - name: Install node
      uses: actions/setup-node@v1
      with: # but that version is important (works on it, doesn't work on earlier ones, wasn't tested on latest ones)
        node-version: 12
    # cache npm deps for faster runs
    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
        collect_analytics: 0
      with:
        path: ~/.npm
        key: npm-${{ runner.os }}-${{ hashFiles('e2e/package-lock.json') }}
        restore-keys: |
          npm-${{ runner.os }}-

    # e2e is a small npm submodule for e2e tests
    - name: Go to e2e dir and init npm using cache
      run: cd e2e && npm ci # `npm ci` is like `npm install` but uses cache from previous step
    - name: Run e2e tests in a headless mode
      run: cd e2e && npm run test:headless

    - name: On failure upload dir with errors to github artifacts
      uses: actions/upload-artifact@master
      if: ${{ failure() }}
      with:
        name: e2e output
        path: e2e/output/