name: "PR labeler"

on:
  workflow_call:

env:
  ACTIONS_STEP_DEBUG: '${{ secrets.ACTIONS_STEP_DEBUG }}'

jobs:
  autolabel:
    name: "PR title"
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2.0.1

      - name: "Validate PR's title"
        uses: thehanimo/pr-title-checker@v1.3.4
        with:
          pass_on_octokit_error: false
          configuration_path: ".github/pr-title-checker-config.json"
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: "Set PR's label based on title"
        uses: release-drafter/release-drafter@v5.20.1
        with:
          disable-releaser: true
          config-name: autolabeler.yml
        env:
          GITHUB_TOKEN: ${{ github.token }}
