name: "Ruff"

on:
  workflow_call:
    inputs:
      head_sha:
        required: true
        type: string

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2.1.0

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.head_sha }}

      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          src: "./label_studio"
          version: 0.0.285
