name: "Ruff"

on:
  workflow_call:
    inputs:
      head_sha:
        required: true
        type: string

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.head_sha }}
    - uses: actions/setup-python@v4
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: ruff --all-files --hook-stage pre-push
