name: Sync PR

on:
  repository_dispatch:
    types:
      - upstream_repo_update

concurrency:
  group: ${{ github.workflow }}-${{ github.event.client_payload.branch_name || 'schedule' }}

env:
  NODE: 14
  CACHE_NAME_PREFIX: v1
  STATIC_DIST: 'label_studio/frontend/dist'
  RELEASE_BRANCH_PREFIX: "ls-release/"

jobs:
  open:
    name: Sync PR
    if: |
      github.event_name != 'schedule' && (
      github.event.client_payload.event_action == 'opened' ||
      github.event.client_payload.event_action == 'synchronize' ||
      github.event.client_payload.event_action == 'merged'
      )
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2.1.0

      - name: Configure git
        shell: bash
        run: |
          set -xeuo pipefail
          git config --global user.name '${{ github.event.client_payload.author_username }}'
          git config --global user.email '${{ github.event.client_payload.author_email }}'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_PAT }}
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}

      - name: Checkout module
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.client_payload.repo_name }}
          path: tmp
          token: ${{ secrets.GIT_PAT }}
          fetch-depth: 1
          ref: ${{ github.event.client_payload.commit_sha }}

      - uses: actions/setup-node@v3
        with:
          node-version: "${{ env.NODE }}"

      - name: Upgrade Yarn
        run: npm install -g yarn@1.22

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Configure yarn cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ env.CACHE_NAME_PREFIX }}-${{ runner.os }}-node-${{ env.NODE }}-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/yarn.lock') }}

      - name: Print Yarn cache size
        run: du -d 0 -h ${{ steps.yarn-cache-dir-path.outputs.dir }}

      - name: Install dependencies
        run: |
          rm package-lock.json || true
          yarn install
        working-directory: tmp

      - name: Build module
        run: |
          yarn run build:module
          if [[ "${{ github.event.client_payload.event_action }}" == 'merged' ]]; then 
            branch="${{ github.event.client_payload.base_branch_name }}"
          else
            branch="${{ github.event.client_payload.branch_name }}"
          fi
          cat << EOF > "build/static/version.json"
          {
            "message": "${{ github.event.client_payload.title }}",
            "commit": "${{ github.event.client_payload.commit_sha }}",
            "branch": "${branch}",
            "date": "$(git log -1 --date=format:"%Y/%m/%d %T" --format="%ad" | cat)"
          }
          EOF

        working-directory: tmp
        env:
          CI: false # on true webpack breaks on warnings, and we have them a lot
          NODE_ENV: 'production'

      - name: Get PR
        uses: actions/github-script@v6
        id: get-pr
        with:
          github-token: ${{ secrets.GIT_PAT }}
          script: |
            const {repo, owner} = context.repo;
            const branchName = '${{ github.event.client_payload.branch_name }}';
            const branchNameLowerCase = branchName.toLowerCase();
            const {data: listPullsResponse} = await github.rest.pulls.list({
              owner,
              repo,
              head: `${owner}:${branchName}`,
              per_page: 1
            });
            const {data: listPullsResponseLowerCase} = await github.rest.pulls.list({
              owner,
              repo,
              head: `${owner}:${branchNameLowerCase}`,
              per_page: 1
            });
            
            if (listPullsResponse.length !== 0) {
              console.log(`Found PR for branch '${branchName}'`)
              core.setOutput("branch-name", branchName);
              return listPullsResponse
            } else if (listPullsResponseLowerCase.length !== 0) {
              console.log(`Found PR for branch '${branchNameLowerCase}'`)
              core.setOutput("branch-name", branchNameLowerCase);
              return listPullsResponseLowerCase
            } else {
              console.log(`PR for branch '${branchNameLowerCase}' is not created yet`)
              core.setOutput("branch-name", branchNameLowerCase);
              return listPullsResponseLowerCase
            }

      - name: Create branch
        shell: bash
        run: |
          set -xeuo pipefail
          
          branch_name='${{ steps.get-pr.outputs.branch-name }}'
          
          if grep -q '^${{ env.RELEASE_BRANCH_PREFIX }}.*$' <<< '${{ github.event.client_payload.base_branch_name }}'; then
            git checkout '${{ github.event.client_payload.base_branch_name }}'
          else
            git checkout '${{ github.event.repository.default_branch }}'
          fi

          git checkout "${branch_name}" || true
          git checkout -b "${branch_name}" || true

          if [[ "${{ github.event.client_payload.repo_name }}" == */dm2* ]]; then 
            module_dist="${{ env.STATIC_DIST }}/dm"
          elif [[ "${{ github.event.client_payload.repo_name }}" == */label-studio-frontend* ]]; then
            module_dist="${{ env.STATIC_DIST }}/lsf"
          else
            echo "Repo ${{ github.event.client_payload.repo_name }} is not supported"
            exit 1
          fi
          
          rm -rf "${module_dist}"
          mkdir -p "${module_dist}"
          cp -r tmp/build/static/* "${module_dist}"

          ls tmp/build/static/
          ls "${module_dist}"

          git add "${{ env.STATIC_DIST }}"
          git status -s
          git commit --allow-empty -m '[submodules] Build static ${{ github.event.client_payload.repo_name }}'
          git push origin HEAD

      - name: Create PR
        id: create-pr
        uses: actions/github-script@v6
        env:
          TITLE: ${{ github.event.client_payload.title }}
          RELEASE_BRANCH_PREFIX: "${{ env.RELEASE_BRANCH_PREFIX }}"
        with:
          github-token: ${{ secrets.GIT_PAT }}
          script: |
            const { repo, owner } = context.repo;
            const branchName = '${{ steps.get-pr.outputs.branch-name }}';
            const listPullsResponse = ${{ steps.get-pr.outputs.result }}
            if (listPullsResponse.length) {
              core.info(`PR already exist ${ listPullsResponse[0].html_url }`)
              if ( listPullsResponse[0].body.includes('${{ github.event.client_payload.html_url }}') ) {
                core.info(`${{ github.event.client_payload.html_url }} already referenced in PR description`)
                return listPullsResponse
              } else {
                core.info(`Adding new ref on ${{ github.event.client_payload.html_url }} to PR`)
                const newBody = listPullsResponse[0].body + `\n- ${{ github.event.client_payload.html_url }}`
                const updatePullResponse = await github.rest.pulls.update({
                  title: process.env.TITLE,
                  owner,
                  repo,
                  pull_number: listPullsResponse[0].number,
                  body: newBody
                });
                return updatePullResponse
              }
            } else {
              let base = '${{ github.event.repository.default_branch }}'
              if ( '${{ github.event.client_payload.base_branch_name }}'.startsWith(process.env.RELEASE_BRANCH_PREFIX) ) {
                base = '${{ github.event.client_payload.base_branch_name }}'
              }
              const createPullResponse = await github.rest.pulls.create({
                title: process.env.TITLE,
                owner,
                repo,
                head: branchName,
                base: base,
                draft: true,
                body: [
                  'Hi @${{ github.event.client_payload.actor }}!',
                  '',
                  'This PR was created in response to a PRs in upstream repo:',
                  '- ${{ github.event.client_payload.html_url }}',
                ].join('\n')
              });
              return createPullResponse
            }

      - name: Check all submodules
        id: check-all-submodules
        if: github.event.client_payload.event_action == 'merged'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GIT_PAT }}
          result-encoding: string
          script: |
            const branchName = '${{ github.event.client_payload.branch_name }}';
            const branchNameLowerCase = branchName.toLowerCase();

            const submodules = [
              { owner: 'heartexlabs', repo: 'label-studio-frontend' },
              { owner: 'heartexlabs', repo: 'dm2' }
            ]
            let openPRs = []  
            for (let submodule of submodules) {
              core.info(`Checking ${ submodule.owner }/${ submodule.repo }`)
              const listAllOpenPulls = await github.paginate(
                github.rest.pulls.list,
                {
                  owner: submodule.owner,
                  repo: submodule.repo,
                  status: 'open',
                  per_page: 100
                },
                (response) => response.data
              );
              
              const listOpenPulls = listAllOpenPulls.filter(e => e.head.ref.toLowerCase() === branchNameLowerCase)

              for (let pr of listOpenPulls) {
                if ( submodule.hasOwnProperty('paths-ignore') ) {
                  core.info(`Checking ${ submodule.owner }/${ submodule.repo } for ignore files`)
                  const getCommitResponse = await github.rest.repos.getCommit({
                    owner: submodule.owner,
                    repo: submodule.repo,
                    ref: pr.merge_commit_sha
                  });
                  if ( getCommitResponse.data.files.every(e => e.filename.startsWith(submodule['paths-ignore'])) ) {
                    core.info(`Skiping ${ pr.html_url } since it only change ${ submodule['paths-ignore'] } files`)
                    continue
                  }
                }
                openPRs.push(pr)
              }
            }
            
            if ( openPRs.length === 0 ) {
              return true
            } else {
              let comment_lines = ['To enable Auto Merge for this PR also merge those PRs:']
              core.info(`Found ${ openPRs.length } open PRs`)
              for (let pr of openPRs) {
                core.info(`${ pr.html_url } is not merged yet`)
                comment_lines.push(`- ${ pr.html_url }`)
              } 
              return comment_lines.join('\n')
            }

      - name: Comment PR
        if: |
          github.event.client_payload.event_action == 'merged' &&
          steps.check-all-submodules.outputs.result != 'true'
        id: comment-pr
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GIT_PAT }}
          script: |
            const { repo, owner } = context.repo;
            const listPullsResponse = ${{ steps.get-pr.outputs.result }}
            github.rest.issues.createComment({
              owner,
              repo,
              issue_number: listPullsResponse[0].number,
              body: `${{ steps.check-all-submodules.outputs.result }}`,
            });

      - name: Convert to ready for review
        if: |
          github.event.client_payload.event_action == 'merged' &&
          steps.check-all-submodules.outputs.result == 'true'
        id: ready-for-review-pr
        shell: bash
        env:
          GIT_PAT: ${{ secrets.GIT_PAT }}
        run: |
          echo "$GIT_PAT" | gh auth login --with-token
          gh api graphql -F id='${{ fromJson(steps.get-pr.outputs.result)[0].node_id }}' -f query='
            mutation($id: ID!) {
              markPullRequestReadyForReview(input: { pullRequestId: $id }) {
                pullRequest {
                  id
                }
              }
            }
          '

      - name: Enable AutoMerge
        id: enable-pr-automerge
        if: |
          github.event.client_payload.event_action == 'merged' &&
          steps.check-all-submodules.outputs.result == 'true'
        shell: bash
        env:
          GIT_PAT: ${{ secrets.GIT_PAT }}
        run: |
          echo "$GIT_PAT" | gh auth login --with-token
          gh api graphql -f pull='${{ fromJson(steps.get-pr.outputs.result)[0].node_id }}' -f query='
            mutation($pull: ID!) {
              enablePullRequestAutoMerge(input: {pullRequestId: $pull, mergeMethod: SQUASH}) {
                pullRequest {
                  id
                  number
                }
              }
            }'

  others:
    name: Other actions with PR
    if: |
      github.event_name != 'schedule' && (
      github.event.client_payload.event_action == 'converted_to_draft' ||
      github.event.client_payload.event_action == 'ready_for_review' ||
      github.event.client_payload.event_action == 'closed'
      )
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2.1.0

      - name: Get PR
        uses: actions/github-script@v6
        id: get-pr
        with:
          github-token: ${{ secrets.GIT_PAT }}
          script: |
            const {repo, owner} = context.repo;
            const branchName = '${{ github.event.client_payload.branch_name }}';
            const branchNameLowerCase = branchName.toLowerCase();
            const {data: listPullsResponse} = await github.rest.pulls.list({
              owner,
              repo,
              head: `${owner}:${branchName}`,
              per_page: 1
            });
            const {data: listPullsResponseLowerCase} = await github.rest.pulls.list({
              owner,
              repo,
              head: `${owner}:${branchNameLowerCase}`,
              per_page: 1
            });
            
            if (listPullsResponse.length !== 0) {
              console.log(`Found PR for branch '${branchName}'`)
              core.setOutput("branch-name", branchName);
              return listPullsResponse
            } else if (listPullsResponseLowerCase.length !== 0) {
              console.log(`Found PR for branch '${branchNameLowerCase}'`)
              core.setOutput("branch-name", branchNameLowerCase);
              return listPullsResponseLowerCase
            } else {
              console.log(`PR for branch '${branchNameLowerCase}' is not created yet`)
              core.setOutput("branch-name", branchNameLowerCase);
              return listPullsResponseLowerCase
            }

      - name: Close PR
        if: github.event.client_payload.event_action == 'closed'
        id: close-pr
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GIT_PAT }}
          script: |
            const { repo, owner } = context.repo;
            const listPullsResponse = ${{ steps.get-pr.outputs.result }}
            for (let pr of listPullsResponse ) {
              core.info(`Closing ${ pr.html_url }`)
              github.rest.pulls.update({
                owner,
                repo,
                pull_number: pr.number,
                state: 'close'
              });
            }

      - name: Convert to draft
        if: github.event.client_payload.event_action == 'converted_to_draft'
        id: convert-pr-to-draft
        shell: bash
        env:
          GIT_PAT: ${{ secrets.GIT_PAT }}
        run: |
          echo "$GIT_PAT" | gh auth login --with-token
          gh api graphql -F id='${{ fromJson(steps.get-pr.outputs.result)[0].node_id }}' -f query='
            mutation($id: ID!) {
              convertPullRequestToDraft(input: { pullRequestId: $id }) {
                pullRequest {
                  id
                  isDraft
                }
              }
            }
          '

      - name: Convert to ready for review
        if: github.event.client_payload.event_action == 'ready_for_review'
        id: ready-for-review-pr
        shell: bash
        env:
          GIT_PAT: ${{ secrets.GIT_PAT }}
        run: |
          echo "$GIT_PAT" | gh auth login --with-token
          gh api graphql -F id='${{ fromJson(steps.get-pr.outputs.result)[0].node_id }}' -f query='
            mutation($id: ID!) {
              markPullRequestReadyForReview(input: { pullRequestId: $id }) {
                pullRequest {
                  id
                }
              }
            }
          '
